# Generated by Django 6.1 on 2026-08-31 20:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount billed for this transaction.', max_digits=12)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='SUCCESS', max_length=20)),
                ('simulated_gateway_ref', models.CharField(help_text='Deterministic or unique mock payment gateway reference ID.', max_length=100, unique=True)),
                ('error_message', models.TextField(blank=True, default='', help_text='Gateway decline reason or error description if payment failed.')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transaction', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
