# Generated by Django 6.1 on 2026-08-31 20:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, help_text='Unique client-supplied idempotency key (e.g. UUID header).', max_length=255)),
                ('request_path', models.CharField(max_length=255)),
                ('request_hash', models.CharField(help_text='SHA-256 hash of the request body and parameters.', max_length=64)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('response_code', models.PositiveIntegerField(blank=True, help_text='HTTP response status code returned by the operation.', null=True)),
                ('response_body', models.JSONField(blank=True, help_text='Cached serialized JSON response body.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Idempotency Key',
                'verbose_name_plural': 'Idempotency Keys',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='unique_user_idempotency_key')],
            },
        ),
    ]
